apps/registros/urls.py
from django.conf.urls import url

from apps.registros.views import ticket_crear, ticket_listar, ticket_detalle

urlpatterns = [
    url(r'^listar$', ticket_listar, name='ticket-listar'),
    url(r'^crear$', ticket_crear, name='ticket-crear'),
    url(r'^detalle/(?P<pk_ticket>\d+)$', ticket_detalle, name='ticket-detalle'),
]

apps/usuarios/urls.py
from django.conf.urls import url

from apps.usuarios.views import index

urlpatterns = [
    url(r'^$', index, name='index'),
    ##url(r'^solicitud/listar$', login_required(SolicitudList.as_view()), name='solicitud_listar'),
]

desafio_desarrollo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import logout_then_login, login

urlpatterns = [
    url(r'^', include('apps.usuarios.urls', namespace="usuarios_namespace")),
    url(r'^admin/', admin.site.urls),
    url(r'^registros/', include('apps.registros.urls', namespace="registros_namespace")),

    url(r'^accounts/login/', login , {'template_name':'index.html'}, name="login"),
    url(r'^logout/', logout_then_login , name="logout"),
]

apps/registros/models.py
from django.db import models
from django.utils import timezone

class ticket(models.Model):

    ## Tupla con opciones para el campo estado
    opciones_estado = (
        ('A', 'Abierto'),
        ('P', 'Pendiente'),
        ('E', 'En Proceso'),
        ('C', 'Cerrado'),
    )

    titulo = models.CharField(max_length=250, null=False, verbose_name="Título")
    descripcion = models.CharField(max_length=250, null=False, verbose_name="Descripción")
    estado = models.CharField(max_length=1, choices=opciones_estado, blank=True)
    fecha_creacion = models.DateField(default=timezone.now)

apps/usuarios/models.py
from django.db import models

# Create your models here.

apps/registros/forms.py
from django import forms

from apps.registros.models import ticket


class ticket_form(forms.ModelForm):

    class Meta:
        model = ticket

        exclude = (
            'fecha_creacion',
        )

        fields = (
            'titulo',
            'descripcion',
            'estado',
        )

        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'required': 'required'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'required': 'required'}),
            'estado': forms.Select(attrs={'class': 'form-control', 'required': 'required'}),
        }

apps/usuarios/forms.py
from django import forms

apps/registros/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.db.models import F
from django.db.models.functions import ExtractDay
from django.shortcuts import render, redirect
from apps.registros.forms import ticket_form
from apps.registros.models import ticket

@login_required()
def ticket_crear(request):
    """
    View habilitada para crear un ticket
    :param request (POST): formulario ticket_form
    :return (template): vista crear o listar
    """

    ## Variable que almacena las variable para template
    data = dict()

    if request.method == 'POST':
        form = ticket_form(request.POST)
        if form.is_valid():
            form.save()
            return redirect('registros_namespace:ticket-listar')
    else:
        form = ticket_form()


    data['form'] = form

    return render(request, 'registros/ticket_crear.html', data)


@login_required()
def ticket_listar(request):
    """
    View habilitada para listar ticket
    :param request (): -
    :return (template): listar
    """

    ## Variable que almacena las variable para template
    data = dict()

    ## Obtengo los ticket y agrego en la queryset los dias transcurridos desde su publicacion
    data['lista_ticket'] = ticket.objects.annotate(dias_transcurridos=ExtractDay(datetime.datetime.now()-F('fecha_creacion')))

    return render(request, 'registros/ticket_listar.html', data)

@login_required()
def ticket_detalle(request, pk_ticket):
    """
    View habilitada para mostar los detalles de un ticket
    :param request (): -
    :param pk_ticket (int): pk de un ticket
    :return (template): detalles
    """

    ## Variable que almacena las variable para template
    data = dict()

    ticket_solicitado = ticket.objects.filter(pk=int(pk_ticket))

    ##Valido si se encontro el ticket solicitado
    if ticket_solicitado.count()!=0:
        data['form']=ticket_form(instance=ticket_solicitado[0])
        data['ticked_id'] = ticket_solicitado[0].pk

    ## Si el ticket no se encontro se vuelve a la vista de listar
    else:
        ##Se notifica al usuario que no existe el ticket pedido
        data['mensaje'] = 'Ticket no encontrado'
        return render(request, 'registros/ticket_listar.html', data)

    return render(request, 'registros/ticket_detalle.html', data)

apps/usuarios/views.py
from django.shortcuts import render, redirect

def index(request):
    """
    Funcion que carga la vista para hacer login a la plataforma
    :param request (POST): username and password
    :return (template): login o home
    """
    data = dict()

    if request.method=='POST':
        print('Post')
    else:
        print('Get')

    return render(request,'index.html',data)

apps/registros/templates/registros/ticket_crear.html
{% extends "base/base.html" %}

{% block tittle %}
	Crear Ticket
{% endblock %}

{% block container %}
    <!-- -->
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal">Sistema de Ticket's</h5>
        <nav class="my-2 my-md-0 mr-md-3"></nav>
        <a href="{% url 'registros_namespace:ticket-listar' %}" class="btn btn-outline-success">Volver</a>
        <a class="btn btn-outline-primary" href="{% url 'logout' %}">Salir</a>
    </div>

    <div class="row">
        <div class="col-12">
            <form method="post">
				{% csrf_token %}

                <div class="row">
                    <div class="col-4 offset-4 form-group">
                        <h2>Ingresar</h2>
                    </div>
                    <div class="col-4 offset-4 form-group">
                        {{form.as_table}}
                    </div>
                    <div class="col-4 offset-4 form-group">
                        <button type="submit" class="btn btn-success">Crear</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

apps/registros/templates/registros/ticket_detalle.html
{% extends "base/base.html" %}

{% block tittle %}
	Detalle Ticket
{% endblock %}

{% block container %}
    <!-- -->
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal">Sistema de Ticket's</h5>
        <nav class="my-2 my-md-0 mr-md-3"></nav>
        <a href="{% url 'registros_namespace:ticket-listar' %}" class="btn btn-outline-success">Volver</a>
        <a class="btn btn-outline-primary" href="{% url 'logout' %}">Salir</a>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="row">
                <div class="col-4 offset-4 form-group">
                    <h2>Ticket # {{ticked_id}}</h2>
                </div>
                <div class="col-4 offset-4 form-group">
                    {{form.as_table}}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block jsFiles %}
    <script>
        $(document).ready(function() {
            $('#id_titulo').prop( "disabled",true);
            $('#id_descripcion').prop( "disabled",true);
            $('#id_estado').prop( "disabled",true);
        });
    </script>
{% endblock %}

apps/registros/templates/registros/ticket_listar.html
{% extends "base/base.html" %}

{% block tittle %}
Lista ded Ticket
{% endblock %}

{% block container %}
<!-- -->
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">Sistema de Ticket's</h5>
    <nav class="my-2 my-md-0 mr-md-3"></nav>
    {% if request.user.is_superuser %}
    <a href="{% url 'registros_namespace:ticket-crear' %}" class="btn btn-outline-success">Crear Ticket</a>
    {% endif %}
    <a class="btn btn-outline-primary" href="{% url 'logout' %}">Salir</a>
</div>

<div class="row">
    <div class="col-6 offset-3">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Título</th>
                <th scope="col">Descripción</th>
                <th scope="col">Estado</th>
                <th scope="col">Publicado hace</th>
                <th scope="col">Detalles</th>
            </tr>
            </thead>
            <tbody>
            {% for ticket in lista_ticket %}
            <tr>
                <th scope="row">{{ticket.pk}}</th>
                <td>{{ticket.titulo|title}}</td>
                <td>{{ticket.descripcion|truncatechars:10}}</td>
                <td>{{ticket.get_estado_display}}</td>
                <td>
                    {% if ticket.dias_transcurridos == 0%}
                    Menos de un día
                    {% else %}
                    {{ticket.dias_transcurridos }} días
                    {% endif %}
                </td>
                <td><a href="{% url 'registros_namespace:ticket-detalle' ticket.pk %}"
                       class="btn btn-primary">Detalles</a></td>
            </tr>
            {% empty %}
            <tr>
                <th scope="row" colspan="6"> No hay ticket's</th>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>

<html lang="es">
	<head>
		<!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>{% block tittle %}Document{% endblock %}</title>

		{% block cssFiles %}
		{% endblock %}

      	<!--Import css from Bootstrap-->
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	</head>
	<body>

    <div class="container-fluid">
        {% block container %}{% endblock %}
    </div>

	<!--Import js from JQuery -->
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>

	<!--Import js from Bootstrap -->
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

	{% block jsFiles %}
	{% endblock %}
	</body>
</html>

templates/index.html
{% extends "base/base.html" %}

{% block tittle %}
	Ingresar
{% endblock %}

{% block container %}
    <!-- -->
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal">Sistema de Ticket's</h5>
        <nav class="my-2 my-md-0 mr-md-3"></nav>
        <a class="btn btn-outline-primary" href="#">Sign up</a>
    </div>

    <div class="row">
        <div class="col-12">
            <form method="post">
				{% csrf_token %}

                <div class="row">
                    <div class="col-4 offset-4 form-group">
                        <h2>Ingresar</h2>
                    </div>
                    <div class="col-4 offset-4 form-group">
                        <label for="last_name">Nombre de usuario</label>
                        <input type="text" id="last_name" name="username" class="form-control" required>
                    </div>
                    <div class="col-4 offset-4 form-group">
                        <label for="pass">Contraseña</label>
                        <input type="password" id="pass" name="password" class="form-control" required>
                    </div>

                    {% if form.errors %}
                        <div class="col-4 offset-4 form-group">
                            <div class="alert alert-danger" role="alert">
                              {{form.errors}}
                            </div>
                        </div>
                    {% endif %}
                    <div class="col-4 offset-4 form-group">
                        <button type="submit" class="btn btn-info">Ingresar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- -->
    <footer class="text-muted">
        <div class="container">
        </div>
    </footer>
{% endblock %}